<?php

/**
 * @file
 * Main functions of the module.
 */

use Drupal\Core\Config\Entity\ConfigEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\navigation\Plugin\SectionStorage\NavigationSectionStorage;
use Drupal\node\NodeInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\taxonomy\TermInterface;
use Drupal\taxonomy\VocabularyInterface;
use Drupal\tour\Entity\Tour;
use Drupal\tour\RenderCallbacks;

/**
 * Implements hook_help().
 */
function tour_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.tour') {
    $output = '<h2>' . t('About') . '</h2>';
    $output .= '<p>' . t("The Tour module provides users with guided tours of the site interface. Each tour consists of several tips that highlight elements of the user interface, guide the user through a workflow, or explain key concepts of the website. For more information, see the <a href=':tour'>online documentation for the Tour module</a>.", [':tour' => 'https://www.drupal.org/documentation/modules/tour']) . '</p>';
    $output .= '<h2>' . t('Uses') . '</h2>';
    $output .= '<dl>';
    $output .= '<dt>' . t('Viewing tours') . '</dt>';
    $output .= '<dd>' . t("If a tour is available on a page, a <em>Tour</em> button will be visible in the toolbar. If you click this button the first tip of the tour will appear. The tour continues after clicking the <em>Next</em> button in the tip. To see a tour users must have the permission <em>Access tour</em> and JavaScript must be enabled in the browser") . '</dd>';
    $output .= '<dt>' . t('Creating tours') . '</dt>';
    $output .= '</dl>';
    return $output;
  }
}

/**
 * Implements hook_theme().
 */
function tour_theme(): array {
  return [
    // List views.
    'tour_listing_table' => [
      'variables' => [
        'headers' => NULL,
        'rows' => NULL,
        'empty' => NULL,
        'attributes' => [],
      ],
    ],
    'navigation_tour' => [
      'variables' => [
        'type' => NULL,
        'tag' => NULL,
        'value' => NULL,
        'attributes' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_toolbar().
 */
function tour_toolbar(): array {
  $items = [];
  $items['tour'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

  if (!\Drupal::currentUser()->hasPermission('access tour')) {
    return $items;
  }

  // Load all the items and match on route name.
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();

  // Check if the current matching path is the front page.
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    $route_name = '<front>';
  }

  $results = \Drupal::entityQuery('tour')
    ->condition('routes.*.route_name', $route_name);

  if ($route_match->getRouteObject()) {
    foreach ($route_match->getParameters() as $name => $parameter) {
      if ($parameter instanceof EntityInterface && is_numeric($parameter->id())) {
        $results->condition('routes.*.route_params.' . $name, $parameter->id());
        break;
      }
      elseif ($parameter instanceof ConfigEntityInterface) {
        $name = $name === 'dashboard' ? 'id' : $name;
        $results->condition('routes.*.route_params.' . $name, $parameter->id());
        break;
      }
    }
  }

  $results = $results->condition('status', TRUE)
    ->accessCheck(FALSE)
    ->execute();
  $no_tips = empty($results);

  $items['tour'] += [
    '#type' => 'toolbar_item',
    'tab' => [
      '#lazy_builder' => [
        'tour.lazy_builders:renderTour',
        [$no_tips],
      ],
      '#cache' => ['contexts' => ['url']],
    ],
    '#wrapper_attributes' => [
      'class' => ['tour-toolbar-tab'],
    ],
    '#attached' => [
      'library' => [
        'tour/tour',
      ],
    ],
  ];

  // \Drupal\toolbar\Element\ToolbarItem::preRenderToolbarItem adds an
  // #attributes property to each toolbar item's tab child automatically.
  // Lazy builders don't support an #attributes property, so we need to
  // add another render callback to remove the #attributes property. We start by
  // adding the defaults, and then we append our own pre render callback.
  $items['tour'] += \Drupal::service('plugin.manager.element_info')->getInfo('toolbar_item');
  $items['tour']['#pre_render'][] = [RenderCallbacks::class, 'removeTabAttributes'];

  return $items;
}

/**
 * Implements hook_page_bottom().
 */
function tour_page_bottom(array &$page_bottom): void {
  if (!\Drupal::currentUser()->hasPermission('access tour')) {
    return;
  }

  // Load all the items and match on route name.
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();

  // Check if the current matching path is the front page.
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    $route_name = '<front>';
  }

  $results = \Drupal::entityQuery('tour')
    ->condition('routes.*.route_name', $route_name)
    ->condition('status', TRUE)
    ->execute();
  if (!empty($results) && $tours = Tour::loadMultiple(array_keys($results))) {
    foreach ($tours as $id => $tour) {
      // Get the parameters.
      $params = $route_match->getRawParameters()->all();
      // Include 'bundle' as parameter to use as match.
      // You could also add additional if (example a node has a specific field).
      if (($node = $route_match->getParameter('node')) && ($node instanceof NodeInterface)) {
        $params['bundle'] = $node->bundle();
      }
      if (($node_type = $route_match->getParameter('node_type')) && ($node_type instanceof NodeTypeInterface)) {
        $params['bundle'] = $node_type->get('type');
      }
      // Get the Taxonomy Vocabulary.
      if (($vocab = $route_match->getParameter('taxonomy_vocabulary')) && ($vocab instanceof VocabularyInterface)) {
        $params['bundle'] = $vocab->id();
      }
      // Get the Taxonomy Vocabulary from a term.
      if (($term = $route_match->getParameter('taxonomy_term')) && ($term instanceof TermInterface)) {
        $params['bundle'] = $term->bundle();
      }
      // Get the id of dashboard from dashboard config entity.
      if (($dashboard = $route_match->getParameter('dashboard')) && $dashboard instanceof ConfigEntityInterface) {
        $params['id'] = $dashboard->id();
      }
      // Match on the parameters.
      if (!$tour->hasMatchingRoute($route_name, $params)) {
        unset($tours[$id]);
      }
    }
    if (!empty($tours)) {
      $page_bottom['tour'] = \Drupal::entityTypeManager()
        ->getViewBuilder('tour')
        ->viewMultiple($tours);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for tour entities.
 */
function tour_tour_insert($entity): void {
  \Drupal::service('plugin.manager.tour.tip')->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_update() for tour entities.
 */
function tour_tour_update($entity): void {
  \Drupal::service('plugin.manager.tour.tip')->clearCachedDefinitions();
}

/**
 * Implements hook_tour_tips_alter().
 */
function tour_tour_tips_alter(array $tour_tips, EntityInterface $entity): void {
  if (\Drupal::service('module_handler')->moduleExists('language')) {
    foreach ($tour_tips as $tour_tip) {
      if ($tour_tip->get('id') == 'language-overview') {
        if (Drupal::service('module_handler')->moduleExists('locale')) {
          $additional_overview = t("This page also provides an overview of how much of the site's interface has been translated for each configured language.");
        }
        else {
          $additional_overview = t("If the Interface Translation module is installed, this page will provide an overview of how much of the site's interface has been translated for each configured language.");
        }
        $tour_tip->set('body', $tour_tip->get('body') . '<br>' . $additional_overview);
      }
      elseif ($tour_tip->get('id') == 'language-continue') {
        $additional_continue = '';
        $additional_modules = [];
        if (!Drupal::service('module_handler')->moduleExists('locale')) {
          $additional_modules[] = \Drupal::service('extension.list.module')->getName('locale');
        }
        if (!Drupal::service('module_handler')->moduleExists('content_translation')) {
          $additional_modules[] = \Drupal::service('extension.list.module')->getName('content_translation');
        }
        if (!empty($additional_modules)) {
          $additional_continue = t('Depending on your site features, additional modules that you might want to install are:') . '<ul>';
          foreach ($additional_modules as $additional_module) {
            $additional_continue .= '<li>' . $additional_module . '</li>';
          }
          $additional_continue .= '</ul>';
        }
        if (!empty($additional_continue)) {
          $tour_tip->set('body', $tour_tip->get('body') . '<br>' . $additional_continue);
        }
      }
    }
  }

  if (\Drupal::service('module_handler')->moduleExists('dblog')) {
    foreach ($tour_tips as $tour_tip) {
      if ($tour_tip->get('id') == 'dblog-more-information') {
        $body = $tour_tip->get('body');
        // Tips can reference the help page conditionally, only create the link
        // if the help module is enabled, else remove it.
        if (\Drupal::moduleHandler()->moduleExists('help')) {
          $body = str_replace('[help.page.dblog]', '<a href="' . Url::fromRoute('help.page', ['name' => 'dblog'])->toString() . '">the help text</a> and ', $body);
        }
        else {
          $body = str_replace('[help.page.dblog]', '', $body);
        }
        $tour_tip->set('body', $body);
      }
    }
  }
}

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 *
 * Curate the blocks available in the Layout Builder "Add Block" UI.
 */
function tour_plugin_filter_block__layout_builder_alter(array &$definitions, array $extra): void {
  if (($extra['section_storage'] ?? NULL) instanceof NavigationSectionStorage) {
    if (!isset($definitions['navigation_tour'])) {
      $definitions['navigation_tour'] = [
        'class' => "Drupal\tour\Plugin\Block\NavigationTourBlock",
        "provider" => "tour",
        "id" => "navigation_tour",
        "category" => "Navigation",
        'admin_label' => t('Tour'),
      ];
    }
  }
}

/**
 * Implements hook_block_alter().
 */
function tour_block_alter(&$definitions): void {
  if (isset($definitions['navigation_tour'])) {
    $definitions['navigation_tour']['_block_ui_hidden'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function tour_preprocess_navigation_tour(&$variables): void {
  // @todo Remove when D10 support is dropped.
  $variables['navigation_sdc'] = FALSE;
  if (str_starts_with(\Drupal::VERSION, '11') && !str_contains(\Drupal::VERSION, '-dev') && \Drupal::VERSION > '11.0.5') {
    $variables['navigation_sdc'] = TRUE;
  }
  elseif (str_starts_with(\Drupal::VERSION, '10') && \Drupal::VERSION > '10.3.6') {
    $variables['navigation_sdc'] = TRUE;
  }
}
